let user1 = prompt("melumatinizi daxil edin")
console.log(user1.length)
let user2 = prompt("melumatinizi daxil edin")
console.log(user2.includes("e"))
let user3 = prompt("melumatinizi daxil edin")
console.log(user3.startsWith("code"))
let user4 = prompt("melumatinizi daxil edin")
console.log(user4.endsWith("code"))
let user5 = prompt("melumatinizi daxil edin")
console.log(user5.replaceAll("t","####"))
